### ISSUE TITLE
New code implement as Python 3 cause torrenttv plugin not work !

### ISSUE THREAD

**Issue by aperfeito** [pepsik-kiev/HTTPAceProxy#12]
Hi Pepsik-Kiev,

    I test your improve code about Python 3 and cause this error below when you loading your server with this commands:

     python acehttp.py
                  or

     phyton2 acehttp.py

and ...

vlc http://192.168.5.144:8000/torrenttv/playlist.m3u

Both commands loading the server ok like as said before but when you using the plugin torrenttv cause this error

torrenttv_plugin.py  [LINE:87  ]# ERROR    [05.08 18:20:42]  Traceback (most recent call last):
  File "plugins/torrenttv_plugin.py", line 44, in downloadPlaylist
    origin = requests.get(config.url, headers=headers, proxies=config.proxies, timeout=30).text
  File "/home/aperfeito/Downloads/Proxy2/HTTPAceProxy/modules/wheels/requests-2.19.1-py2.py3-none-any.whl/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/aperfeito/Downloads/Proxy2/HTTPAceProxy/modules/wheels/requests-2.19.1-py2.py3-none-any.whl/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/aperfeito/Downloads/Proxy2/HTTPAceProxy/modules/wheels/requests-2.19.1-py2.py3-none-any.whl/requests/sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "/home/aperfeito/Downloads/Proxy2/HTTPAceProxy/modules/wheels/requests-2.19.1-py2.py3-none-any.whl/requests/sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/aperfeito/Downloads/Proxy2/HTTPAceProxy/modules/wheels/requests-2.19.1-py2.py3-none-any.whl/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/home/aperfeito/Downloads/Proxy2/HTTPAceProxy/modules/wheels/requests-2.19.1-py2.py3-none-any.whl/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

acehttp.py           [LINE:74  ]# ERROR    [05.08 18:20:42]  Dying with error

Plugin allfon is working ok with improve code

I have your server written with old code its fine both plugins

**Comment by pepsik-kiev** [comment]
????? I use proxy on Python3 with the /torrenttv.py plugin in daily use  - ZERO problems 
All works fine with all included plugins. I tested working capacity in Python 2.7.15 & 3.6.5 . I also have feedback from other users that everything works as it should. The error that you submitted relates to the requests module - did you update it from git ? Did you correctly fill out the parameter
`# Insert your Torrent-tv.ru playlist URL here                                                                                                              
url=`
in /plugin/config/torrenttv.py ?

**Comment by aperfeito** [comment]
Hi Pepsik,
  when I pull your new code from here i forget the fill the parameters you mentioned  'url=' in /plugins/config/torrenttv.py ?

    Your Right ! 
Now All fine running in Python 3 Yeah !
