### ISSUE TITLE
Traceback: errors

### ISSUE THREAD

**Issue by XJIOP** [pepsik-kiev/HTTPAceProxy#14]
After stop playing video, sometimes get such errors
```
acehttp.py           [LINE:204 ]# INFO     [13.08 15:41:43]  Streaming "***" to 192.168.1.105 finished
aceclient.py         [LINE:118 ]# DEBUG    [13.08 15:41:43]  >>> EVENT stop
aceclient.py         [LINE:104 ]# DEBUG    [13.08 15:41:43]  Destroying AceStream client.....
aceclient.py         [LINE:118 ]# DEBUG    [13.08 15:41:43]  >>> SHUTDOWN
acehttp.py           [LINE:207 ]# WARNING  [13.08 15:41:43]  Broadcast "***" stoped. Last client disconnected
aceclient.py         [LINE:254 ]# DEBUG    [13.08 15:41:43]  All clients disconnected - broadcast stoped
aceclient.py         [LINE:275 ]# DEBUG    [13.08 15:41:43]  Close video stream: http://127.0.0.1:6878/content/***/0.452407847868
aceclient.py         [LINE:302 ]# DEBUG    [13.08 15:41:43]  <<< RESUME
aceclient.py         [LINE:118 ]# DEBUG    [13.08 15:41:43]  >>> EVENT play
aceclient.py         [LINE:302 ]# DEBUG    [13.08 15:41:43]  <<< STATE 2
aceclient.py         [LINE:302 ]# DEBUG    [13.08 15:41:43]  <<< STATE 0
aceclient.py         [LINE:302 ]# DEBUG    [13.08 15:41:43]  <<< SHUTDOWN
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/opt/acestream/HTTPAceProxy/aceclient/aceclient.py", line 384, in _recvData
    self._recvbuffer = self._socket.read_all()
  File "/usr/lib/python2.7/telnetlib.py", line 385, in read_all
    self.fill_rawq()
  File "/usr/lib/python2.7/telnetlib.py", line 576, in fill_rawq
    buf = self.sock.recv(50)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_socket2.py", line 289, in recv
    return sock.recv(*args)
error: [Errno 104] Connection reset by peer
2018-08-13T13:41:43Z <Greenlet "Greenlet-0" at 0xb58d8470L: <bound method AceClient._recvData of <aceclient.aceclient.AceClient object at 0xb5884fd0>>> failed with error
```

**Comment by pepsik-kiev** [comment]
I can not reproduce this error. Need more information about what version of the python is used, in all broadcasts it is observed? What version of gevent is installed? What player is used for viewing broadcasts? 
Based on the provided log, try to comment the line 
`#self._recvbuffer = self._socket.read_all()` in /aceclient/aceclient.py  
Will this error occur?
