### ISSUE TITLE
PlugIn TorrentFilms report Phython 3 is  Fast ....

### ISSUE THREAD

**Issue by aperfeito** [pepsik-kiev/HTTPAceProxy#17]
Hi Pepsik-kiev

  I been test here your code improvements and here what's happend.

Line command: `vlc http://10.177.65.70:8000/proxyfilms`

 and the Folder called Torrents setup in settings of the plugin has 2 Films below : 

```
[aperfeito@alarm Torrents]$ ls
a0bde9b7e64dba671c03d1c047ef8a21965cdaa4.torrent
c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb.torrent
[aperfeito@alarm Torrents]$
```

The VLC Show up everything the list of 2 films and i can watch the film normally but the proxy has this behaviour:
`
acehttp.py           [LINE:187 ]# WARNING  [27.08 11:35:55]  Create a broadcast "Rampage.2018.720p.WEBRip.x264-[YTS.AM].mp4"`

`acehttp.py           [LINE:200 ]# INFO     [27.08 11:36:37]  Streaming "Rampage.2018.720p.WEBRip.x264-[YTS.AM].mp4" to 10.177.65.70 started`

 and.. after waching about 2 minutes look 

```
aceclient.py         [LINE:245 ]# DEBUG    [27.08 11:37:05]  Disconnecting client: 10.177.65.70
aceclient.py         [LINE:256 ]# ERROR    [27.08 11:37:05]  Unexpected error in streamreader
aceclient.py         [LINE:257 ]# ERROR    [27.08 11:37:05]  Traceback (most recent call last):
  File "/home/aperfeito/Downloads/Proxy2/HTTPAceProxy/aceclient/aceclient.py", line 242, in startStreamReader
    try: c.queue.put(data, timeout=5)
  File "src/gevent/queue.py", line 243, in gevent._queue.Queue.put
  File "src/gevent/queue.py", line 276, in gevent._queue.Queue.put
  File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
queue.Full

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aperfeito/Downloads/Proxy2/HTTPAceProxy/aceclient/aceclient.py", line 246, in startStreamReader
    c.destroy()
AttributeError: 'Client' object has no attribute 'destroy'

aceclient.py         [LINE:270 ]# DEBUG    [27.08 11:37:05]  Close video stream: http://127.0.0.1:6878/content/c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb/0.480604923863
aceclient.py         [LINE:101 ]# DEBUG    [27.08 11:37:05]  Destroying AceStream client.....
aceclient.py         [LINE:115 ]# DEBUG    [27.08 11:37:05]  >>> SHUTDOWN
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/aperfeito/Downloads/Proxy2/HTTPAceProxy/aceclient/aceclient.py", line 264, in startStreamReader
    counter.deleteAll(cid)
  File "/home/aperfeito/Downloads/Proxy2/HTTPAceProxy/aceclient/clientcounter.py", line 101, in deleteAll
    for c in clients: c.destroy()
AttributeError: 'Client' object has no attribute 'destroy'
2018-08-27T18:37:05Z <Greenlet "Greenlet-0" at 0xb564a540: <bound method AceClient.startStreamReader of <aceclient.aceclient.AceClient object at 0xb4ab6eb0>>('http://127.0.0.1:6878/content/c5a9fe3ff9672b6fb1d, 'c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb', <aceclient.clientcounter.ClientCounter object at 0, {'Host': '10.177.65.70:8000', 'Accept': '*/*', 'Ac)> failed with AttributeError

aceclient.py         [LINE:291 ]# DEBUG    [27.08 11:37:05]  <<< STATE 0
aceclient.py         [LINE:291 ]# DEBUG    [27.08 11:37:05]  <<< SHUTDOWN
aceclient.py         [LINE:358 ]# DEBUG    [27.08 11:37:05]  AceClient destroyed
```

but the film continues normally !!! 

Information about the system here !

[aperfeito@alarm Torrents]$ python -V
Python 3.7.0
[aperfeito@alarm Torrents]$ pip list 
Package      Version
------------ -------
anytree      2.4.3  
appdirs      1.4.3  
Beaker       1.10.0 
btrfsutil    1.0.0  
CacheControl 0.12.5 
chardet      3.0.4  
colorama     0.3.9  
distlib      0.2.7  
distro       1.3.0  
docutils     0.14   
gevent       1.3.6  
greenlet     0.4.14 
html5lib     1.0.1  
idna         2.7    
lensfun      0.3.2  
lockfile     0.12.2 
lxml         4.2.4  
Mako         1.0.7  
MarkupSafe   1.0    
msgpack      0.5.6  
namcap       3.2.7  
packaging    17.1   
pip          18.0   
progress     1.4    
psutil       5.4.6  
pyalpm       0.8    
pyelftools   0.24   
Pygments     2.2.0  
pyparsing    2.2.0  
pytoml       0.1.16 
requests     2.19.1 
retrying     1.3.3  
setuptools   40.2.0 
six          1.11.0 
team         1.0    
urllib3      1.23   
webencodings 0.5.1  
[aperfeito@alarm Torrents]$ 

PS: I did my best

**Comment by pepsik-kiev** [comment]
Are you sure that you are using the latest version HTTPAceProxy ?

**Comment by aperfeito** [comment]
HI Pepsik-Kiev,

  For your Information this is the version I tested:

```

   drwxr-xr-x 3 aperfeito users  4096 Aug 26 19:52 aceclient
-rw-r--r-- 1 aperfeito users  7920 Aug 23 11:06 aceconfig.py
-rw-r--r-- 1 aperfeito users  3276 Aug 26 19:52 aceconfig.pyc
-rw-r--r-- 1 aperfeito users  2168 Aug 23 10:59 acedefconfig.py
-rw-r--r-- 1 aperfeito users  2896 Aug 26 19:52 acedefconfig.pyc
-rwxr-xr-x 1 aperfeito users 24149 Aug 23 10:59 acehttp.py
drwxr-xr-x 4 aperfeito users  4096 Aug 26 19:52 modules
drwxr-xr-x 4 aperfeito users  4096 Aug 26 19:52 plugins
drwxr-xr-x 2 aperfeito users  4096 Aug 27 11:16 __pycache__
-rw-r--r-- 1 aperfeito users   829 Aug  5 13:43 README.md
drwxr-xr-x 2 aperfeito users  4096 Aug 26 19:48 Torrents
```

**Comment by aperfeito** [comment]
Hi Pepsik-kiev,

After performing the update for this version below 

```
[aperfeito@alarm HTTPAceProxy]$ ls -l
total 68
drwxr-xr-x 3 aperfeito users  4096 Aug 28 16:10 aceclient
-rw-r--r-- 1 aperfeito users  7920 Aug 23 11:06 aceconfig.py
-rw-r--r-- 1 aperfeito users  3276 Aug 26 19:52 aceconfig.pyc
-rw-r--r-- 1 aperfeito users  2117 Aug 28 16:10 acedefconfig.py
-rw-r--r-- 1 aperfeito users  2896 Aug 26 19:52 acedefconfig.pyc
-rwxr-xr-x 1 aperfeito users 23045 Aug 28 16:10 acehttp.py
drwxr-xr-x 4 aperfeito users  4096 Aug 28 16:10 modules
drwxr-xr-x 4 aperfeito users  4096 Aug 28 16:10 plugins
drwxr-xr-x 2 aperfeito users  4096 Aug 28 16:22 __pycache__
-rw-r--r-- 1 aperfeito users   979 Aug 28 16:10 README.md
drwxr-xr-x 2 aperfeito users  4096 Aug 31 08:03 Torrents
```
The file torrent The second torrent in your example
{"status": 1, "files": [["Jason.Bourne.2016.720p.WEBRip.x264.AAC-ETRG.mp4", 2]], "infohash": "a0bde9b7e64dba671c03d1c047ef8a21965cdaa4", "checksum": "f786fd6f2535344fc5978832475ae60eed73989a"}

NOW this happend

acehttp.py           [LINE:92  ]# INFO     [31.08 08:07:23]  Accepted connection from 172.16.109.152 path /proxyfilms
acehttp.py           [LINE:93  ]# DEBUG    [31.08 08:07:23]  Headers: {'User-Agent': 'mpv 0.28.0-139-gdba143de4d', 'Accept': '*/*', 'Range': 'bytes=0-', 'Connection': 'close', 'Host': '172.16.109.152:8000', 'Icy-MetaData': '1'}
torrentfilms_plugin.py [LINE:59  ]# DEBUG    [31.08 08:07:23]  c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb.torrent
torrentfilms_plugin.py [LINE:59  ]# DEBUG    [31.08 08:07:23]  a0bde9b7e64dba671c03d1c047ef8a21965cdaa4.torrent
torrentfilms_plugin.py [LINE:101 ]# INFO     [31.08 08:07:23]  Torrent  playlist created
acehttp.py           [LINE:92  ]# INFO     [31.08 08:07:23]  Accepted connection from 172.16.109.152 path /infohash/a0bde9b7e64dba671c03d1c047ef8a21965cdaa4/0/stream.mp4
acehttp.py           [LINE:93  ]# DEBUG    [31.08 08:07:23]  Headers: {'User-Agent': 'mpv 0.28.0-139-gdba143de4d', 'Accept': '*/*', 'Range': 'bytes=0-', 'Connection': 'close', 'Host': '172.16.109.152:8000', 'Icy-MetaData': '1'}
clientcounter.py     [LINE:25  ]# DEBUG    [31.08 08:07:23]  Create connection to AceEngine.....
aceclient.py         [LINE:77  ]# DEBUG    [31.08 08:07:23]  Successfully connected to AceStream on 127.0.0.1:62062
aceclient.py         [LINE:110 ]# DEBUG    [31.08 08:07:23]  >>> HELLOBG version=3
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:07:23]  <<< HELLOTS version=3.1.30 version_code=3013000 key=0d3bbbf16d http_port=6878 bmode=0
aceclient.py         [LINE:110 ]# DEBUG    [31.08 08:07:23]  >>> READY key=n51LvQoTlJzNGaFxseRK-e666de681eef3fcdad254d63fefd2ff178175c09
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:07:23]  <<< AUTH 0
aceclient.py         [LINE:110 ]# DEBUG    [31.08 08:07:23]  >>> SETOPTIONS use_stop_notifications=1
aceclient.py         [LINE:110 ]# DEBUG    [31.08 08:07:23]  >>> LOADASYNC 39202 INFOHASH a0bde9b7e64dba671c03d1c047ef8a21965cdaa4 0 0 0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:07:23]  <<< STATUS main:loading
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:07:23]  <<< LOADRESP 39202 {"status": 1, "files": [["Jason.Bourne.2016.720p.WEBRip.x264.AAC-ETRG.mp4", 2]], "infohash": "a0bde9b7e64dba671c03d1c047ef8a21965cdaa4", "checksum": "f786fd6f2535344fc5978832475ae60eed73989a"}
acehttp.py           [LINE:75  ]# ERROR    [31.08 08:07:23]  Unkonwn exception: IndexError('list index out of range')
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:07:23]  <<< STATUS main:idle


I tested the file torrent in peerflix and plays well 

What's happend ?

**Comment by aperfeito** [comment]
Hi Pepsik-kiev,

  After many tries in the second archive torrent in this new version AceProxy look below what happend : 

I checked torrent from your log -
{"status": 1, "files": [["Rampage.2018.720p.WEBRip.x264-[YTS.AM].mp4", 0]], "infohash": "c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb", "checksum": "b49c72780f414dba4c0a3bc139b8139fcf570417"}
Now look !!! 


```
acehttp.py           [LINE:498 ]# INFO     [31.08 08:54:07]  Server started at 172.16.109.152:8000 Use <Ctrl-C> to stop
acehttp.py           [LINE:92  ]# INFO     [31.08 08:54:13]  Accepted connection from 172.16.109.152 path /proxyfilms
acehttp.py           [LINE:93  ]# DEBUG    [31.08 08:54:13]  Headers: {'Host': '172.16.109.152:8000', 'Accept': '*/*', 'Accept-Language': 'en_US', 'User-Agent': 'VLC/4.0.0-dev LibVLC/4.0.0-dev', 'Range': 'bytes=0-'}
torrentfilms_plugin.py [LINE:59  ]# DEBUG    [31.08 08:54:13]  c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb.torrent
torrentfilms_plugin.py [LINE:101 ]# INFO     [31.08 08:54:13]  Torrent  playlist created
acehttp.py           [LINE:92  ]# INFO     [31.08 08:54:13]  Accepted connection from 172.16.109.152 path /infohash/c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb/0/stream.mp4
acehttp.py           [LINE:93  ]# DEBUG    [31.08 08:54:13]  Headers: {'Host': '172.16.109.152:8000', 'Accept': '*/*', 'Accept-Language': 'en_US', 'User-Agent': 'VLC/4.0.0-dev LibVLC/4.0.0-dev', 'Range': 'bytes=0-'}
clientcounter.py     [LINE:25  ]# DEBUG    [31.08 08:54:13]  Create connection to AceEngine.....
aceclient.py         [LINE:77  ]# DEBUG    [31.08 08:54:13]  Successfully connected to AceStream on 127.0.0.1:62062
aceclient.py         [LINE:110 ]# DEBUG    [31.08 08:54:13]  >>> HELLOBG version=3
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:14]  <<< HELLOTS version=3.1.30 version_code=3013000 key=2fb9803944 http_port=6878 bmode=0
aceclient.py         [LINE:110 ]# DEBUG    [31.08 08:54:14]  >>> READY key=n51LvQoTlJzNGaFxseRK-533ea6f7d88293fd1f498397ad6e9988b510acb4
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:14]  <<< AUTH 0
aceclient.py         [LINE:110 ]# DEBUG    [31.08 08:54:14]  >>> SETOPTIONS use_stop_notifications=1
aceclient.py         [LINE:110 ]# DEBUG    [31.08 08:54:14]  >>> LOADASYNC 10394 INFOHASH c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb 0 0 0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:14]  <<< STATUS main:loading
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:14]  <<< LOADRESP 10394 {"status": 1, "files": [["Rampage.2018.720p.WEBRip.x264-[YTS.AM].mp4", 0]], "infohash": "c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb", "checksum": "b49c72780f414dba4c0a3bc139b8139fcf570417"}
acehttp.py           [LINE:180 ]# WARNING  [31.08 08:54:14]  Create a broadcast "Rampage.2018.720p.WEBRip.x264-[YTS.AM].mp4"
aceclient.py         [LINE:110 ]# DEBUG    [31.08 08:54:14]  >>> START INFOHASH c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb 0 0 0 0 output_format=http
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:14]  <<< STATUS main:idle
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:14]  <<< STATE 1
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:14]  <<< STATUS main:starting
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:15]  <<< STATUS main:prebuf;0;2147477212;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:17]  <<< STATUS main:prebuf;0;2147477212;0;0;0;0;0;4;0;0;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:19]  <<< STATUS main:prebuf;0;27493;0;0;30;0;0;4;0;163840;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:21]  <<< STATUS main:prebuf;5;5626;0;0;86;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:23]  <<< STATUS main:prebuf;5;8983;0;0;67;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:25]  <<< STATUS main:prebuf;5;12339;0;0;55;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:27]  <<< STATUS main:prebuf;5;15696;0;0;47;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:29]  <<< STATUS main:prebuf;5;19054;0;0;40;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:31]  <<< STATUS main:prebuf;5;22411;0;0;36;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:33]  <<< STATUS main:prebuf;5;25765;0;0;32;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:35]  <<< STATUS main:prebuf;5;29138;0;0;29;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:37]  <<< STATUS main:prebuf;5;32724;0;0;26;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:39]  <<< STATUS main:prebuf;5;36668;0;0;24;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:41]  <<< STATUS main:prebuf;5;41111;0;0;21;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:44]  <<< STATUS main:prebuf;5;45897;0;0;19;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:45]  <<< STATUS main:prebuf;5;51346;0;0;18;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:48]  <<< STATUS main:prebuf;5;57171;0;0;16;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:50]  <<< STATUS main:prebuf;5;63574;0;0;14;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:52]  <<< STATUS main:prebuf;5;70786;0;0;13;0;0;3;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:54]  <<< STATUS main:prebuf;5;78563;0;0;12;0;0;4;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:56]  <<< STATUS main:prebuf;5;87230;0;0;11;0;0;4;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:54:58]  <<< STATUS main:prebuf;5;96670;0;0;10;0;0;4;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:00]  <<< STATUS main:prebuf;5;107061;0;0;9;0;0;4;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:02]  <<< STATUS main:prebuf;5;118748;0;0;8;0;0;4;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:04]  <<< STATUS main:prebuf;5;131365;0;0;7;0;0;4;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:06]  <<< STATUS main:prebuf;5;145448;0;0;6;0;0;4;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:08]  <<< STATUS main:prebuf;5;160798;0;0;6;0;0;4;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:10]  <<< STATUS main:prebuf;5;177644;0;0;5;0;0;4;0;638976;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:12]  <<< STATUS main:prebuf;5;196597;0;0;5;0;0;5;0;638976;0;0
acehttp.py           [LINE:75  ]# ERROR    [31.08 08:55:14]  AceClient exception: AceException('Engine response time exceeded. getResult timeout from 127.0.0.1:62062')
aceclient.py         [LINE:110 ]# DEBUG    [31.08 08:55:14]  >>> STOP
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:14]  <<< STATE 0
aceclient.py         [LINE:110 ]# DEBUG    [31.08 08:55:14]  >>> EVENT stop 
acehttp.py           [LINE:198 ]# WARNING  [31.08 08:55:14]  Broadcast "Rampage.2018.720p.WEBRip.x264-[YTS.AM].mp4" stoped. Last client disconnected
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:14]  <<< STATUS main:idle
acehttp.py           [LINE:92  ]# INFO     [31.08 08:55:14]  Accepted connection from 172.16.109.152 path /infohash/c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb/0/stream.mp4
acehttp.py           [LINE:93  ]# DEBUG    [31.08 08:55:14]  Headers: {'Host': '172.16.109.152:8000', 'User-Agent': 'VLC/4.0.0-dev LibVLC/4.0.0-dev', 'Icy-MetaData': '1'}
aceclient.py         [LINE:110 ]# DEBUG    [31.08 08:55:14]  >>> LOADASYNC 96692 INFOHASH c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb 0 0 0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:14]  <<< STATUS main:loading
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:14]  <<< LOADRESP 96692 {"status": 1, "files": [["Rampage.2018.720p.WEBRip.x264-[YTS.AM].mp4", 0]], "infohash": "c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb", "checksum": "b49c72780f414dba4c0a3bc139b8139fcf570417"}
acehttp.py           [LINE:180 ]# WARNING  [31.08 08:55:14]  Create a broadcast "Rampage.2018.720p.WEBRip.x264-[YTS.AM].mp4"
aceclient.py         [LINE:110 ]# DEBUG    [31.08 08:55:14]  >>> START INFOHASH c5a9fe3ff9672b6fb1d19a978969374e98a1a7cb 0 0 0 0 output_format=http
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:14]  <<< STATUS main:idle
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:14]  <<< STATE 1
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:14]  <<< STATUS main:starting
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:16]  <<< STATUS main:prebuf;0;2147477212;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:18]  <<< STATUS main:prebuf;0;2147477212;0;0;0;0;0;1;0;0;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:20]  <<< STATUS main:prebuf;0;2147477212;0;0;0;0;0;1;0;0;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:22]  <<< STATUS main:prebuf;0;2147477212;0;0;0;0;0;1;0;0;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:24]  <<< STATUS main:prebuf;0;2147477212;0;0;0;0;0;1;0;0;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:26]  <<< STATUS main:prebuf;0;2147477212;0;0;0;0;0;1;0;0;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:28]  <<< STATUS main:prebuf;0;2147477212;0;0;0;0;0;1;0;0;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:30]  <<< STATUS main:prebuf;0;2147477212;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:295 ]# DEBUG    [31.08 08:55:32]  <<< STATUS main:prebuf;0;2147477212;0;0;0;0;0;0;0;0;0;0
^CKeyboardInterrupt
2018-08-31T15:55:33Z
acehttp.py           [LINE:389 ]# INFO     [31.08 08:55:33]  Shutdown server.....
acehttp.py           [LINE:393 ]# INFO     [31.08 08:55:33]  Bye Bye .....
```
 

I myself shutdown the server only to you see what happend with packages looks like the losses himself I don know !!!

this plays well in peerflix too
